### PR TITLE
Update raspibolt_55_explorer.md with btcexplorer v2.0.2

### PR DESCRIPTION
**Pull request by jambolo**
There is a new release for btcrpcexplorer.

This commit updates the tags to v2.0.2

### CODE REVIEW

**Review by lucasmoten — APPROVED** [review]
Code Review ACK
Verified on active node

**Comment by bmml1** [comment]
@jambolo Would you like to do another PR with version 2.1.0 otherwise I would to that.

**Comment by jambolo** [comment]
> @jambolo Would you like to do another PR with version 2.1.0 otherwise I would to that.

Done.

**Comment by jambolo** [comment]
Superseded by PR #678

**Pull request closed without merging**
