### PR TITLE
Update raspibolt_20_pi.md

### PR DESCRIPTION
**Pull request by fatrattombala**
Name of OS has changed
easier way to write image with Raspberry Pi Imager

### CODE REVIEW

**Comment by lucasmoten** [comment]
Thanks. Can you also update 
- references to `Raspbian` in https://github.com/Stadicus/RaspiBolt/blame/master/raspibolt_64_electrum.md#L107
- references to `Raspbian Buster Lite` in https://github.com/Stadicus/RaspiBolt/blame/master/raspibolt_69_tor.md#L39

**Comment by lucasmoten** [comment]
Addresses #691

**Comment by fatrattombala** [comment]
done!

**Comment by fatrattombala** [comment]
> Thanks. Can you also update
> 
>     * references to `Raspbian` in https://github.com/Stadicus/RaspiBolt/blame/master/raspibolt_64_electrum.md#L107
> 
>     * references to `Raspbian Buster Lite` in https://github.com/Stadicus/RaspiBolt/blame/master/raspibolt_69_tor.md#L39

done!

**Review by lucasmoten — APPROVED** [review]
LGTM

**Pull request merged**
