### PR TITLE
Update motd and update to LND 0.8.0-beta

### PR DESCRIPTION
**Pull request by 53645714n**
I updated the motd to display the version of bitcoind and lightning and to check for updates and show when an update is available. It does this by checking the -version to the releases/latest on github.
Screenshot from 2019-10-10 14-59-00

I also re-added support for earn.com since my router does not support NAT loopback as do so many others and wrote instructions on how to switch in the manual.

### CODE REVIEW

**Comment by Stadicus** [comment]
Thanks for your contribution! Will test first, probably needs to wait until after Lightning Conference in Berlin.

**Comment by 53645714n** [comment]
> Thanks for your contribution! Will test first, probably needs to wait until after Lightning Conference in Berlin.

No problem, have a greate conference and if you have any questions, just ask.

**Comment by 53645714n** [comment]
I will reopen when I fixed the issue. I need to do a better version check, since the new lnd version had more characters then the old one, it displays a false update flag now.

**Comment by 53645714n** [comment]
Fixed the issue with the version number and added update to LND v0.8.0-beta.

**Comment by 53645714n** [comment]
@Stadicus , I see the version update has been taken care of in another PR, should I close this PR and do another for only the MOTD? (Which might have been better in the first place..)

**Comment by Stadicus** [comment]
Opening an update just for the MOTD would be great, thanks!

**Comment by 53645714n** [comment]
New pPR #505 created

**Pull request closed without merging**
